; Generated by the Jo compiler
section .data

section .rodata
_F0: dq 0x0000000000000000
_F1: dq 0x0000000000000000
_F2: dq 0x0000000000000000
_F3: dq 0x0000000000000000
_F4: dq 0x0000000000000000
_F5: dq 0x0000000000000000
_S0: db 115, 101, 116, 116, 105, 110, 103, 32, 97, 103, 101, 32, 116, 111, 32, 50, 48, 0
_S1: db 10, 0

section .text
global _start

_start:
    xor rbp, rbp
    call main
    mov rdi, 0
    mov rax, 60
    syscall

Person_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov r11, rdi
    mov r10, [r11 + 0]
    mov [rbp - 8], r10
    lea rax, [rbp - 8]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 16], rcx
    lea rax, [rbp - 16]
    mov rax, [rax]
    jmp _epi_Person_new
_epi_Person_new:
    mov rsp, rbp
    pop rbp
    ret

Person_get_age:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax]
    jmp _epi_Person_get_age
_epi_Person_get_age:
    mov rsp, rbp
    pop rbp
    ret

Person_set_age:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov r11, rsi
    mov r10, [r11 + 0]
    mov [rbp - 16], r10
    lea rax, [rel _S0]
    mov [rbp - 32], rax
    mov rax, 17
    mov [rbp - 24], rax
    lea rax, [rbp - 32]
    push rax
    pop rdi
    call print
    mov rax, 20
    mov [rbp - 40], rax
    lea rax, [rbp - 40]
    push rax
    mov rax, [rbp - 8]
    pop rsi
    mov rcx, [rsi + 0]
    mov [rax + 0], rcx
_epi_Person_set_age:
    mov rsp, rbp
    pop rbp
    ret

int_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    lea rax, [rbp - 16]
    mov rax, [rax]
    jmp _epi_int_new
_epi_int_new:
    mov rsp, rbp
    pop rbp
    ret

int_add:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    add rax, qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_add
_epi_int_add:
    mov rsp, rbp
    pop rbp
    ret

int_sub:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    sub rax, qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_sub
_epi_int_sub:
    mov rsp, rbp
    pop rbp
    ret

int_mul:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    imul rax, qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_mul
_epi_int_mul:
    mov rsp, rbp
    pop rbp
    ret

int_div:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cqo
    idiv qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_div
_epi_int_div:
    mov rsp, rbp
    pop rbp
    ret

int_mod_:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cqo
    idiv qword [rbp - 32]
    mov qword [rbp - 40], rdx
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_mod_
_epi_int_mod_:
    mov rsp, rbp
    pop rbp
    ret

int_neg:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, qword [rbp - 16]
    neg rax
    mov qword [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 32], rax
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_int_neg
_epi_int_neg:
    mov rsp, rbp
    pop rbp
    ret

int_eq:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    sete al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_eq
_epi_int_eq:
    mov rsp, rbp
    pop rbp
    ret

int_ne:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setne al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_ne
_epi_int_ne:
    mov rsp, rbp
    pop rbp
    ret

int_lt:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setl al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_lt
_epi_int_lt:
    mov rsp, rbp
    pop rbp
    ret

int_gt:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setg al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_gt
_epi_int_gt:
    mov rsp, rbp
    pop rbp
    ret

int_le:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setle al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_le
_epi_int_le:
    mov rsp, rbp
    pop rbp
    ret

int_ge:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setge al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_int_ge
_epi_int_ge:
    mov rsp, rbp
    pop rbp
    ret

int_not:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, qword [rbp - 16]
    test rax, rax
    setz al
    movzx rax, al
    mov qword [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 32], rax
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_int_not
_epi_int_not:
    mov rsp, rbp
    pop rbp
    ret

int_to_float:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 16], rax
    movsd xmm0, [rel _F0]
    movsd [rbp - 24], xmm0
    cvtsi2sd xmm0, qword [rbp - 16]
    movsd qword [rbp - 24], xmm0
    movsd xmm0, [rbp - 24]
    movsd [rbp - 32], xmm0
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_int_to_float
_epi_int_to_float:
    mov rsp, rbp
    pop rbp
    ret

bool_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    lea rax, [rbp - 16]
    mov rax, [rax]
    jmp _epi_bool_new
_epi_bool_new:
    mov rsp, rbp
    pop rbp
    ret

bool_not:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, qword [rbp - 16]
    xor rax, 1
    mov qword [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 32], rax
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_bool_not
_epi_bool_not:
    mov rsp, rbp
    pop rbp
    ret

bool_and:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    and rax, qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_bool_and
_epi_bool_and:
    mov rsp, rbp
    pop rbp
    ret

bool_or:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    or rax, qword [rbp - 32]
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_bool_or
_epi_bool_or:
    mov rsp, rbp
    pop rbp
    ret

bool_eq:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    sete al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_bool_eq
_epi_bool_eq:
    mov rsp, rbp
    pop rbp
    ret

bool_ne:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setne al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_bool_ne
_epi_bool_ne:
    mov rsp, rbp
    pop rbp
    ret

char_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    lea rax, [rbp - 16]
    mov rax, [rax]
    jmp _epi_char_new
_epi_char_new:
    mov rsp, rbp
    pop rbp
    ret

char_eq:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    sete al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_char_eq
_epi_char_eq:
    mov rsp, rbp
    pop rbp
    ret

char_ne:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, qword [rbp - 24]
    cmp rax, qword [rbp - 32]
    setne al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_char_ne
_epi_char_ne:
    mov rsp, rbp
    pop rbp
    ret

char_to_int:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 24], rax
    lea rax, [rbp - 24]
    mov rax, [rax]
    jmp _epi_char_to_int
_epi_char_to_int:
    mov rsp, rbp
    pop rbp
    ret

float_new:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    movsd [rbp - 8], xmm0
    movsd xmm0, [rbp - 8]
    movsd [rbp - 16], xmm0
    lea rax, [rbp - 16]
    mov rax, [rax]
    jmp _epi_float_new
_epi_float_new:
    mov rsp, rbp
    pop rbp
    ret

float_add:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    movsd xmm0, [rel _F1]
    movsd [rbp - 40], xmm0
    movsd xmm0, qword [rbp - 24]
    addsd xmm0, qword [rbp - 32]
    movsd qword [rbp - 40], xmm0
    movsd xmm0, [rbp - 40]
    movsd [rbp - 48], xmm0
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_add
_epi_float_add:
    mov rsp, rbp
    pop rbp
    ret

float_sub:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    movsd xmm0, [rel _F2]
    movsd [rbp - 40], xmm0
    movsd xmm0, qword [rbp - 24]
    subsd xmm0, qword [rbp - 32]
    movsd qword [rbp - 40], xmm0
    movsd xmm0, [rbp - 40]
    movsd [rbp - 48], xmm0
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_sub
_epi_float_sub:
    mov rsp, rbp
    pop rbp
    ret

float_mul:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    movsd xmm0, [rel _F3]
    movsd [rbp - 40], xmm0
    movsd xmm0, qword [rbp - 24]
    mulsd xmm0, qword [rbp - 32]
    movsd qword [rbp - 40], xmm0
    movsd xmm0, [rbp - 40]
    movsd [rbp - 48], xmm0
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_mul
_epi_float_mul:
    mov rsp, rbp
    pop rbp
    ret

float_div:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    movsd xmm0, [rel _F4]
    movsd [rbp - 40], xmm0
    movsd xmm0, qword [rbp - 24]
    divsd xmm0, qword [rbp - 32]
    movsd qword [rbp - 40], xmm0
    movsd xmm0, [rbp - 40]
    movsd [rbp - 48], xmm0
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_div
_epi_float_div:
    mov rsp, rbp
    pop rbp
    ret

float_neg:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 16], xmm0
    movsd xmm0, [rel _F5]
    movsd [rbp - 24], xmm0
    movsd xmm0, qword [rbp - 16]
    xorpd xmm1, xmm1
    subsd xmm1, xmm0
    movsd qword [rbp - 24], xmm1
    movsd xmm0, [rbp - 24]
    movsd [rbp - 32], xmm0
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_float_neg
_epi_float_neg:
    mov rsp, rbp
    pop rbp
    ret

float_eq:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    sete al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_eq
_epi_float_eq:
    mov rsp, rbp
    pop rbp
    ret

float_ne:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    setne al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_ne
_epi_float_ne:
    mov rsp, rbp
    pop rbp
    ret

float_lt:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    setb al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_lt
_epi_float_lt:
    mov rsp, rbp
    pop rbp
    ret

float_gt:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    seta al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_gt
_epi_float_gt:
    mov rsp, rbp
    pop rbp
    ret

float_le:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    setbe al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_le
_epi_float_le:
    mov rsp, rbp
    pop rbp
    ret

float_ge:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 24], xmm0
    mov rax, [rbp - 16]
    movsd xmm0, [rax + 0]
    movsd [rbp - 32], xmm0
    mov rax, 0
    mov [rbp - 40], rax
    movsd xmm0, qword [rbp - 24]
    movsd xmm1, qword [rbp - 32]
    ucomisd xmm0, xmm1
    setae al
    movzx rax, al
    mov qword [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 48], rax
    lea rax, [rbp - 48]
    mov rax, [rax]
    jmp _epi_float_ge
_epi_float_ge:
    mov rsp, rbp
    pop rbp
    ret

float_to_int:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    movsd xmm0, [rax + 0]
    movsd [rbp - 16], xmm0
    mov rax, 0
    mov [rbp - 24], rax
    movsd xmm0, qword [rbp - 16]
    cvttsd2si rax, xmm0
    mov qword [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 32], rax
    lea rax, [rbp - 32]
    mov rax, [rax]
    jmp _epi_float_to_int
_epi_float_to_int:
    mov rsp, rbp
    pop rbp
    ret

string_new:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 32], rax
    mov rax, [rbp - 16]
    mov [rbp - 24], rax
    lea rax, [rbp - 32]
    mov rdx, [rax + 8]
    mov rax, [rax]
    jmp _epi_string_new
_epi_string_new:
    mov rsp, rbp
    pop rbp
    ret

string_eq:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov rax, [rax + 0]
    mov [rbp - 24], rax
    mov rax, [rbp - 8]
    mov rax, [rax + 8]
    mov [rbp - 32], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 40], rax
    mov rax, [rbp - 16]
    mov rax, [rax + 8]
    mov [rbp - 48], rax
    mov rax, 0
    mov [rbp - 56], rax
    mov rsi, qword [rbp - 24]
    mov rdi, qword [rbp - 40]
    mov rcx, qword [rbp - 32]
    cmp rcx, qword [rbp - 48]
    jne .str_ne
    test rcx, rcx
    jz .str_eq
    .str_loop:
    mov al, [rsi]
    cmp al, [rdi]
    jne .str_ne
    inc rsi
    inc rdi
    dec rcx
    jnz .str_loop
    .str_eq:
    mov qword [rbp - 56], 1
    jmp .str_done
    .str_ne:
    mov qword [rbp - 56], 0
    .str_done:
    mov rax, [rbp - 56]
    mov [rbp - 64], rax
    lea rax, [rbp - 64]
    mov rax, [rax]
    jmp _epi_string_eq
_epi_string_eq:
    mov rsp, rbp
    pop rbp
    ret

string_ne:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    push rax
    mov rax, [rbp - 16]
    push rax
    pop rsi
    pop rdi
    call string_eq
    mov [rbp - 24], rax
    lea rax, [rbp - 24]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 32], rcx
    lea rax, [rbp - 32]
    lea rax, [rbp - 32]
    push rax
    pop rdi
    call bool_not
    mov [rbp - 40], rax
    lea rax, [rbp - 40]
    mov rax, [rax]
    jmp _epi_string_ne
_epi_string_ne:
    mov rsp, rbp
    pop rbp
    ret

string_len:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax + 8]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 24], rax
    lea rax, [rbp - 24]
    mov rax, [rax]
    jmp _epi_string_len
_epi_string_len:
    mov rsp, rbp
    pop rbp
    ret

print:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov r11, rdi
    mov r10, [r11 + 0]
    mov [rbp - 16], r10
    mov r10, [r11 + 8]
    mov [rbp - 8], r10
    lea rax, [rbp - 16]
    mov rax, [rax + 8]
    mov [rbp - 24], rax
    lea rax, [rbp - 16]
    mov rax, [rax + 0]
    mov [rbp - 32], rax
    mov rax, 1 ; write
    mov rdi, 1 ; stdout
    mov rsi, qword [rbp - 32] ; pointer to buffer
    mov rdx, qword [rbp - 24] ; number of bytes
    syscall
    call new_line
_epi_print:
    mov rsp, rbp
    pop rbp
    ret

new_line:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    lea rax, [rel _S1]
    mov [rbp - 16], rax
    mov rax, 1
    mov [rbp - 8], rax
    lea rax, [rbp - 16]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 32], rcx
    mov rcx, [rsi + 8]
    mov [rbp - 24], rcx
    lea rax, [rbp - 32]
    lea rax, [rbp - 32]
    mov rax, [rax + 8]
    mov [rbp - 40], rax
    lea rax, [rbp - 32]
    mov rax, [rax + 0]
    mov [rbp - 48], rax
    mov rax, 1 ; write
    mov rdi, 1 ; stdout
    mov rsi, qword [rbp - 48] ; pointer to buffer
    mov rdx, qword [rbp - 40] ; number of bytes
    syscall
_epi_new_line:
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov rax, 10
    mov [rbp - 8], rax
    lea rax, [rbp - 8]
    push rax
    pop rdi
    call Person_new
    mov [rbp - 16], rax
    lea rax, [rbp - 16]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 24], rcx
    lea rax, [rbp - 24]
    lea rax, [rbp - 24]
    push rax
    pop rdi
    call Person_get_age
    mov [rbp - 32], rax
    lea rax, [rbp - 32]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 40], rcx
    lea rax, [rbp - 40]
    xor rax, rax ; uncallable
    push rax
    pop rdi
    call print
    lea rax, [rbp - 24]
    push rax
    mov rax, 20
    mov [rbp - 64], rax
    lea rax, [rbp - 64]
    push rax
    pop rsi
    pop rdi
    call Person_set_age
    xor rax, rax ; uncallable
    push rax
    pop rdi
    call print
_epi_main:
    mov rsp, rbp
    pop rbp
    ret

malloc:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov r11, rdi
    mov r10, [r11 + 0]
    mov [rbp - 8], r10
    mov rax, 0
    mov [rbp - 16], rax
    lea rax, [rbp - 16]
    mov rsi, rax
    mov rcx, [rsi + 0]
    mov [rbp - 24], rcx
    lea rax, [rbp - 24]
    mov rax, 9 ; mmap
    xor rdi, rdi ; addr = NULL
    mov rsi, qword [rbp - 8] ; length
    mov rdx, 3 ; PROT_READ PROT_WRITE
    mov r10, 34 ; MAP_PRIVATE MAP_ANONYMOUS
    mov r8, - 1
    xor r9, r9
    syscall
    mov qword [rbp - 24], rax
    lea rax, [rbp - 24]
    mov rax, [rax]
    jmp _epi_malloc
_epi_malloc:
    mov rsp, rbp
    pop rbp
    ret

