; Generated by the Jo compiler
section .data

section .rodata
_F0: dq 0x4000000000000000
_F1: dq 0x4020000000000000

section .text
global _start

_start:
    xor rbp, rbp
    call main
    mov rdi, rax
    mov rax, 60
    syscall

f64_half:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    movsd xmm0, [rax]
    sub rsp, 8
    movsd [rsp], xmm0
    movsd xmm0, [rel _F0]
    movsd xmm1, xmm0
    movsd xmm0, [rsp]
    add rsp, 8
    divsd xmm0, xmm1
    jmp _epi_f64_half
_epi_f64_half:
    mov rsp, rbp
    pop rbp
    ret

i64_double:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov rax, [rax]
    push rax
    mov rax, [rbp - 8]
    mov rax, [rax]
    mov rbx, rax
    pop rax
    add rax, rbx
    jmp _epi_i64_double
_epi_i64_double:
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov rax, 21
    mov [rbp - 8], rax
    lea rax, [rbp - 8]
    push rax
    pop rdi
    call i64_double
    mov [rbp - 16], rax
    movsd xmm0, [rel _F1]
    movsd [rbp - 24], xmm0
    lea rax, [rbp - 24]
    push rax
    pop rdi
    call f64_half
    movsd [rbp - 32], xmm0
    mov rax, [rbp - 16]
    jmp _epi_main
_epi_main:
    mov rsp, rbp
    pop rbp
    ret

