//! x86-64 NASM code generator for Jo (System V AMD64 ABI, Linux).
//!
//! Assumes the AST is fully type-checked and desugared: literals are
//! `StructInit`s, operators/casts are `Call`s, and every `Expr` carries a `ty`.
//!
//! Stack-slot assignment uses a pre-pass (`FrameBuilder`) that allocates a
//! fixed `[rbp - offset]` slot for every parameter, every `let`, and every
//! `StructInit` temporary, keyed by the AST node's stable pointer identity.
//! The emitter then looks offsets up by pointer — no fragile positional cursor.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::*;

pub struct CodeGen {
    structs: HashMap<String, StructDecl>,
    primitive_methods: HashMap<String, Vec<FnDecl>>,
    floats: Vec<(String, u64)>,
    strings: Vec<(String, String)>,
    label_counter: usize,
    text: String,
}

impl CodeGen {
    pub fn emit(program: &Program) -> String {
        let mut structs = HashMap::new();
        let mut primitive_methods: HashMap<String, Vec<FnDecl>> = HashMap::new();
        for item in &program.items {
            if let Item::Struct(s) = item {
                structs.insert(s.name.clone(), s.clone());
            }
            if let Item::Extend(e) = item {
                let sname = e.name.clone();
                if is_primitive_extend_target(&sname) {
                    primitive_methods
                        .entry(sname)
                        .or_default()
                        .extend(e.methods.clone());
                    continue;
                }
                if !structs.contains_key(&sname) {
                    continue;
                }
                for m in &e.methods {
                    structs.get_mut(&sname).unwrap().methods.push(m.clone());
                }
            }
        }
        let mut cg = CodeGen {
            structs: structs.clone(),
            primitive_methods: primitive_methods.clone(),
            floats: Vec::new(),
            strings: Vec::new(),
            label_counter: 0,
            text: String::new(),
        };

        let mut main_ret: Option<Type> = None;
        for s in structs.values() {
            for m in &s.methods {
                cg.emit_fn(m, Some(s.name.clone()));
            }
        }
        for (primitive, methods) in &primitive_methods {
            for m in methods {
                cg.emit_fn(m, Some(primitive.clone()));
            }
        }
        for item in &program.items {
            match item {
                Item::Fn(f) => {
                    if f.name == "main" {
                        main_ret = Some(f.return_type.clone());
                    }
                    cg.emit_fn(f, None);
                }
                Item::Struct(_) => {}
                Item::Import(_) => {}
                Item::Extend(_) => {}
            }
        }

        cg.assemble(main_ret.as_ref())
    }

    /// Emit the process entry point. `ld` enters at `_start`; we call `main`,
    /// translate its return value into an exit code, and invoke `exit` (60).
    fn emit_start(&mut self, main_ret: &Type) {
        let mut s = String::new();
        let _ = writeln!(s, "_start:");
        let _ = writeln!(s, "    xor rbp, rbp"); // mark outermost frame
        let _ = writeln!(s, "    call main");
        match main_ret {
            Type::I64 => {
                let _ = writeln!(s, "    mov rdi, rax");
            }
            Type::Named(n) if n == "int" => {
                // `int` is a one-word struct returned by value: rax already holds
                // `inner_value` (see `emit_return`'s struct-return handling).
                let _ = writeln!(s, "    mov rdi, rax");
            }
            _ => {
                let _ = writeln!(s, "    mov rdi, 0");
            }
        }
        let _ = writeln!(s, "    mov rax, 60");
        let _ = writeln!(s, "    syscall");
        let _ = writeln!(s);
        // Prepend so `_start` is the very first thing in .text (defensive: the
        // entry symbol is explicit, but keeping it first avoids surprises).
        self.text.insert_str(0, &s);
    }

    fn assemble(&mut self, main_ret: Option<&Type>) -> String {
        // Emit the `_start` stub (prepended to .text) if a main was found.
        if let Some(ret) = main_ret {
            self.emit_start(ret);
        }

        let mut out = String::new();
        let _ = writeln!(out, "; Generated by the Jo compiler");
        let _ = writeln!(out, "section .data");
        let _ = writeln!(out);
        let _ = writeln!(out, "section .rodata");
        for (label, bits) in &self.floats {
            let _ = writeln!(out, "{}: dq 0x{:016x}", label, bits);
        }
        for (label, bytes) in &self.strings {
            let _ = writeln!(out, "{}: db {}", label, nasm_byte_list(bytes));
        }
        let _ = writeln!(out);
        let _ = writeln!(out, "section .text");
        let _ = writeln!(out, "global _start");
        let _ = writeln!(out);
        out.push_str(&self.text);
        out
    }

    fn new_label(&mut self) -> String {
        let l = format!("_L{}", self.label_counter);
        self.label_counter += 1;
        l
    }

    fn add_float(&mut self, value: f64) -> String {
        let label = format!("_F{}", self.floats.len());
        self.floats.push((label.clone(), value.to_bits()));
        label
    }

    fn add_string(&mut self, value: &str) -> String {
        let label = format!("_S{}", self.strings.len());
        self.strings.push((label.clone(), value.to_string()));
        label
    }

    // --- struct layout -------------------------------------------------------

    fn field_index(&self, struct_name: &str, field: &str) -> usize {
        self.structs
            .get(struct_name)
            .and_then(|s| s.fields.iter().position(|f| f.name == field))
            .unwrap_or(0)
    }

    fn field_decl_type(&self, struct_name: &str, field: &str) -> Type {
        self.structs
            .get(struct_name)
            .and_then(|s| s.fields.iter().find(|f| f.name == field))
            .map(|f| f.ty.clone())
            .unwrap_or(Type::I64)
    }

    fn n_fields(&self, struct_name: &str) -> usize {
        self.structs
            .get(struct_name)
            .map(|s| s.fields.len())
            .unwrap_or(1)
    }

    fn find_method(&self, type_name: &str, method: &str) -> Option<&FnDecl> {
        self.structs
            .get(type_name)
            .and_then(|s| s.methods.iter().find(|m| m.name == method))
            .or_else(|| {
                self.primitive_methods
                    .get(type_name)
                    .and_then(|methods| methods.iter().find(|m| m.name == method))
            })
    }

    fn has_method(&self, type_name: &str, method: &str) -> bool {
        self.find_method(type_name, method).is_some()
    }

    fn size_of(&self, ty: &Type) -> i64 {
        match ty {
            Type::I64 | Type::F64 | Type::Null => 8,
            Type::Ref(_) | Type::MutRef(_) => 8,
            Type::Named(n) | Type::Qualified(_, n) => (self.n_fields(n).max(1) as i64) * 8,
            Type::Void => 0,
        }
    }

    // --- function emission ---------------------------------------------------

    fn emit_fn(&mut self, f: &FnDecl, enclosing_struct: Option<String>) {
        let label = match &enclosing_struct {
            Some(s) => format!("{}_{}", s, f.name),
            None => f.name.clone(),
        };

        // Pass 1: lay out the frame.
        let mut frame = FrameBuilder {
            cg: self,
            next_offset: 0,
            slots: HashMap::new(),
        };
        frame.alloc_params(f, enclosing_struct.as_deref());
        frame.walk_block(&f.body);
        let frame_size = round_up_16(frame.next_offset);
        let slots = frame.slots;

        let _ = writeln!(self.text, "{}:", label);
        let _ = writeln!(self.text, "    push rbp");
        let _ = writeln!(self.text, "    mov rbp, rsp");
        if frame_size > 0 {
            let _ = writeln!(self.text, "    sub rsp, {}", frame_size);
        }

        // Non-local (no leading dot) so it is not scoped under stray `_Ln`
        // labels emitted by nested if/while bodies; unique per function.
        let epilogue = format!("_epi_{}", sanitize(&label));

        let mut em = FnEmitter {
            cg: self,
            scopes: vec![HashMap::new()],
            slots: &slots,
            epilogue_label: epilogue.clone(),
            loop_stack: Vec::new(),
            ret_type: f.return_type.clone(),
        };
        em.spill_params(f, enclosing_struct.as_deref());
        em.emit_block(&f.body);

        // Standard epilogue. `main` is an ordinary function; `_start` handles the
        // exit syscall using `main`'s return value.
        let _ = writeln!(self.text, "{}:", epilogue);
        let _ = writeln!(self.text, "    mov rsp, rbp");
        let _ = writeln!(self.text, "    pop rbp");
        let _ = writeln!(self.text, "    ret");
        let _ = writeln!(self.text);
    }
}

// ---------------------------------------------------------------------------
// Slot keys
// ---------------------------------------------------------------------------

/// A stable identity for an AST node that owns a stack slot. We use the node's
/// memory address; the AST is borrowed immutably for the whole of codegen so
/// these pointers stay valid and unique.
type SlotKey = usize;

fn key_of<T>(r: &T) -> SlotKey {
    r as *const T as usize
}

// ---------------------------------------------------------------------------
// Pass 1: frame layout
// ---------------------------------------------------------------------------

struct FrameBuilder<'c> {
    cg: &'c CodeGen,
    next_offset: i64,
    /// node pointer → (offset, slot size in bytes)
    slots: HashMap<SlotKey, i64>,
}

impl<'c> FrameBuilder<'c> {
    fn alloc(&mut self, key: SlotKey, ty: &Type) -> i64 {
        let size = self.cg.size_of(ty).max(8);
        self.next_offset += size;
        self.slots.insert(key, self.next_offset);
        self.next_offset
    }

    fn alloc_size(&mut self, key: SlotKey, size: i64) -> i64 {
        let size = size.max(8);
        self.next_offset += size;
        self.slots.insert(key, self.next_offset);
        self.next_offset
    }

    fn alloc_params(&mut self, f: &FnDecl, enclosing: Option<&str>) {
        for p in &f.params {
            let ty = param_type(p, enclosing);
            self.alloc(key_of(p), &ty);
        }
    }

    fn walk_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.walk_stmt(stmt);
        }
    }

    fn walk_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(l) => {
                self.walk_expr(&l.init);
                let ty =
                    l.ty.clone()
                        .or_else(|| l.init.ty.clone())
                        .unwrap_or(Type::I64);
                self.alloc(key_of(l), &ty);
            }
            Stmt::Assign(a) => {
                self.walk_expr(&a.value);
                match &a.target {
                    LValue::Deref(e, _) => self.walk_expr(e),
                    LValue::Field(e, _, _) => self.walk_expr(e),
                    LValue::Ident(_, _) => {}
                }
            }
            Stmt::Return(r) => {
                if let Some(v) = &r.value {
                    self.walk_expr(v);
                }
            }
            Stmt::If(if_stmt) => {
                for (c, b) in &if_stmt.branches {
                    self.walk_expr(c);
                    self.walk_block(b);
                }
                if let Some(eb) = &if_stmt.else_block {
                    self.walk_block(eb);
                }
            }
            Stmt::While(w) => {
                self.walk_expr(&w.condition);
                self.walk_block(&w.body);
            }
            Stmt::Expr(e) => self.walk_expr(e),
            Stmt::Asm(_) | Stmt::Break(_) | Stmt::Continue(_) => {}
        }
    }

    fn walk_expr(&mut self, expr: &Expr) {
        match &expr.kind {
            ExprKind::StructInit { name, fields } => {
                for (_, fe) in fields {
                    self.walk_expr(fe);
                }
                let nfields = self.cg.n_fields(name.base()).max(fields.len()).max(1);
                self.alloc_size(key_of(expr), nfields as i64 * 8);
            }
            ExprKind::Unary { operand, .. } => self.walk_expr(operand),
            ExprKind::Binary { left, right, .. } => {
                self.walk_expr(left);
                self.walk_expr(right);
            }
            ExprKind::Cast { expr: inner, .. } => self.walk_expr(inner),
            ExprKind::Call { callee, args } => {
                self.walk_expr(callee);
                for a in args {
                    self.walk_expr(a);
                }
                // A call returning a struct yields its value in rax(:rdx); the
                // emitter materializes it into this slot to recover a pointer.
                if let Some(ty) = &expr.ty {
                    if is_struct_type(ty, self.cg) {
                        let nwords = self
                            .cg
                            .n_fields(receiver_struct(ty).unwrap_or_default().as_str());
                        self.alloc_size(key_of(expr), (nwords.max(1) as i64) * 8);
                    }
                }
            }
            ExprKind::Field { object, .. } => self.walk_expr(object),
            ExprKind::Ref { operand, .. } => self.walk_expr(operand),
            ExprKind::Deref { operand } => self.walk_expr(operand),
            _ => {}
        }
    }
}

// ---------------------------------------------------------------------------
// Pass 2: emission
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct VarInfo {
    offset: i64,
    ty: Type,
}

struct FnEmitter<'c> {
    cg: &'c mut CodeGen,
    scopes: Vec<HashMap<String, VarInfo>>,
    slots: &'c HashMap<SlotKey, i64>,
    epilogue_label: String,
    loop_stack: Vec<(String, String)>,
    ret_type: Type,
}

const INT_REGS: [&str; 6] = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];
const FLOAT_REGS: [&str; 8] = [
    "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7",
];

impl<'c> FnEmitter<'c> {
    fn emit(&mut self, line: impl AsRef<str>) {
        let _ = writeln!(self.cg.text, "    {}", line.as_ref());
    }

    fn emit_label(&mut self, label: &str) {
        let _ = writeln!(self.cg.text, "{}:", label);
    }

    fn slot(&self, key: SlotKey) -> i64 {
        *self.slots.get(&key).unwrap_or(&0)
    }

    fn declare(&mut self, name: &str, offset: i64, ty: Type) {
        self.scopes
            .last_mut()
            .unwrap()
            .insert(name.to_string(), VarInfo { offset, ty });
    }

    fn lookup(&self, name: &str) -> Option<&VarInfo> {
        for s in self.scopes.iter().rev() {
            if let Some(v) = s.get(name) {
                return Some(v);
            }
        }
        None
    }

    // --- parameters ----------------------------------------------------------

    fn spill_params(&mut self, f: &FnDecl, enclosing: Option<&str>) {
        let mut int_i = 0usize;
        let mut flt_i = 0usize;
        for p in &f.params {
            let ty = param_type(p, enclosing);
            let offset = self.slot(key_of(p));
            let name = param_name(p);
            match &ty {
                Type::F64 => {
                    let reg = FLOAT_REGS[flt_i];
                    flt_i += 1;
                    self.emit(format!("movsd [rbp - {}], {}", offset, reg));
                }
                // A by-value struct parameter arrives as a *pointer* in an
                // integer register; copy its words inline so the slot holds the
                // struct directly (consistent with struct-typed locals). Use
                // r10/r11 as scratch — never argument registers, so later
                // parameters still in rsi/rdx/... are not clobbered.
                Type::Named(n) | Type::Qualified(_, n) => {
                    let reg = INT_REGS[int_i];
                    int_i += 1;
                    let nwords = self.cg.n_fields(n);
                    self.emit(format!("mov r11, {}", reg));
                    for i in 0..nwords {
                        self.emit(format!("mov r10, [r11 + {}]", i as i64 * 8));
                        self.emit(format!("mov [rbp - {}], r10", offset - i as i64 * 8));
                    }
                }
                _ => {
                    let reg = INT_REGS[int_i];
                    int_i += 1;
                    self.emit(format!("mov [rbp - {}], {}", offset, reg));
                }
            }
            self.declare(&name, offset, ty);
        }
    }

    // --- blocks & statements -------------------------------------------------

    fn emit_block(&mut self, block: &Block) {
        self.scopes.push(HashMap::new());
        for stmt in &block.stmts {
            self.emit_stmt(stmt);
        }
        self.scopes.pop();
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(l) => {
                let ty =
                    l.ty.clone()
                        .or_else(|| l.init.ty.clone())
                        .unwrap_or(Type::I64);
                let offset = self.slot(key_of(l));
                self.store_value(&l.init, &ty, offset);
                self.declare(&l.name, offset, ty);
            }
            Stmt::Assign(a) => self.emit_assign(a),
            Stmt::Return(r) => self.emit_return(r),
            Stmt::If(if_stmt) => self.emit_if(if_stmt),
            Stmt::While(w) => self.emit_while(w),
            Stmt::Break(_) => {
                if let Some((_, end)) = self.loop_stack.last().cloned() {
                    self.emit(format!("jmp {}", end));
                }
            }
            Stmt::Continue(_) => {
                if let Some((start, _)) = self.loop_stack.last().cloned() {
                    self.emit(format!("jmp {}", start));
                }
            }
            Stmt::Expr(e) => self.emit_expr(e),
            Stmt::Asm(a) => self.emit_asm(a),
        }
    }

    /// Evaluate `init` and store it into the slot at `[rbp - offset]`.
    fn store_value(&mut self, init: &Expr, ty: &Type, offset: i64) {
        match ty {
            Type::F64 => {
                self.emit_expr(init);
                self.emit(format!("movsd [rbp - {}], xmm0", offset));
            }
            Type::Named(n) | Type::Qualified(_, n) => {
                let nfields = self.cg.n_fields(n);
                self.emit_expr(init); // rax = pointer to source struct
                self.copy_struct_to_slot(offset, nfields);
            }
            _ => {
                self.emit_expr(init); // rax
                self.emit(format!("mov [rbp - {}], rax", offset));
            }
        }
    }

    /// Copy `nfields` words from the struct pointed to by rax into the slot.
    fn copy_struct_to_slot(&mut self, dest_offset: i64, nfields: usize) {
        self.emit("mov rsi, rax".to_string());
        for i in 0..nfields {
            self.emit(format!("mov rcx, [rsi + {}]", i as i64 * 8));
            self.emit(format!("mov [rbp - {}], rcx", dest_offset - i as i64 * 8));
        }
        self.emit(format!("lea rax, [rbp - {}]", dest_offset));
    }

    fn emit_assign(&mut self, a: &AssignStmt) {
        match &a.target {
            LValue::Ident(name, _) => {
                if let Some(info) = self.lookup(name).cloned() {
                    self.store_value(&a.value, &info.ty, info.offset);
                }
            }
            LValue::Deref(ptr_expr, _) => {
                let vty = a.value.ty.clone().unwrap_or(Type::I64);
                if matches!(vty, Type::F64) {
                    self.emit_expr(&a.value); // xmm0
                    self.emit("sub rsp, 8".to_string());
                    self.emit("movsd [rsp], xmm0".to_string());
                    self.emit_expr(ptr_expr); // rax = pointer
                    self.emit("movsd xmm0, [rsp]".to_string());
                    self.emit("add rsp, 8".to_string());
                    self.emit("movsd [rax], xmm0".to_string());
                } else {
                    self.emit_expr(&a.value);
                    self.emit("push rax".to_string());
                    self.emit_expr(ptr_expr);
                    self.emit("pop rcx".to_string());
                    self.emit("mov [rax], rcx".to_string());
                }
            }
            LValue::Field(obj, field, _) => {
                let obj_ty = obj.ty.clone().unwrap_or(Type::Void);
                let struct_name = receiver_struct(&obj_ty).unwrap_or_default();
                let idx = self.cg.field_index(&struct_name, field);
                let field_ty = self.cg.field_decl_type(&struct_name, field);
                let base = idx as i64 * 8;
                match &field_ty {
                    Type::F64 => {
                        self.emit_expr(&a.value);
                        self.emit("sub rsp, 8".to_string());
                        self.emit("movsd [rsp], xmm0".to_string());
                        self.emit_expr(obj);
                        self.emit("movsd xmm0, [rsp]".to_string());
                        self.emit("add rsp, 8".to_string());
                        self.emit(format!("movsd [rax + {}], xmm0", base));
                    }
                    // Struct-typed field: copy the value's words inline.
                    Type::Named(n) | Type::Qualified(_, n) => {
                        let nwords = self.cg.n_fields(n);
                        self.emit_expr(&a.value); // rax = pointer to source
                        self.emit("push rax".to_string());
                        self.emit_expr(obj); // rax = destination base pointer
                        self.emit("pop rsi".to_string());
                        for i in 0..nwords {
                            self.emit(format!("mov rcx, [rsi + {}]", i as i64 * 8));
                            self.emit(format!("mov [rax + {}], rcx", base + i as i64 * 8));
                        }
                    }
                    _ => {
                        self.emit_expr(&a.value);
                        self.emit("push rax".to_string());
                        self.emit_expr(obj);
                        self.emit("pop rcx".to_string());
                        self.emit(format!("mov [rax + {}], rcx", base));
                    }
                }
            }
        }
    }

    fn emit_return(&mut self, r: &ReturnStmt) {
        if let Some(v) = &r.value {
            self.emit_expr(v); // rax (pointer for structs / scalar) or xmm0
            // Struct return values are returned *by value* in rax(:rdx) so the
            // result stays valid after our frame is torn down. `emit_expr` left
            // a pointer to the struct in rax; load its words.
            let ret = self.ret_type.clone();
            if is_struct_type(&ret, self.cg) {
                let nwords = self.cg.n_fields(&receiver_struct(&ret).unwrap_or_default());
                self.load_struct_into_regs(nwords);
            }
        }
        let label = self.epilogue_label.clone();
        self.emit(format!("jmp {}", label));
    }

    /// rax holds a pointer to an `nwords`-word struct. Load word 0 → rax and (if
    /// present) word 1 → rdx, the System V small-aggregate return registers.
    fn load_struct_into_regs(&mut self, nwords: usize) {
        match nwords {
            0 | 1 => {
                self.emit("mov rax, [rax]".to_string());
            }
            2 => {
                self.emit("mov rdx, [rax + 8]".to_string());
                self.emit("mov rax, [rax]".to_string());
            }
            n => {
                // >2 words: leave the pointer in rax (best-effort; nested use of
                // such returns is a known v1 limitation).
                let _ = n;
            }
        }
    }

    fn emit_if(&mut self, if_stmt: &IfStmt) {
        let end_label = self.cg.new_label();
        for (cond, block) in &if_stmt.branches {
            let next_label = self.cg.new_label();
            self.emit_expr(cond); // rax = pointer to bool struct
            self.emit("mov rax, [rax]".to_string());
            self.emit("cmp rax, 0".to_string());
            self.emit(format!("je {}", next_label));
            self.emit_block(block);
            self.emit(format!("jmp {}", end_label));
            self.emit_label(&next_label);
        }
        if let Some(eb) = &if_stmt.else_block {
            self.emit_block(eb);
        }
        self.emit_label(&end_label);
    }

    fn emit_while(&mut self, w: &WhileStmt) {
        let start = self.cg.new_label();
        let end = self.cg.new_label();
        self.emit_label(&start);
        self.emit_expr(&w.condition);
        self.emit("mov rax, [rax]".to_string());
        self.emit("cmp rax, 0".to_string());
        self.emit(format!("je {}", end));
        self.loop_stack.push((start.clone(), end.clone()));
        self.emit_block(&w.body);
        self.loop_stack.pop();
        self.emit(format!("jmp {}", start));
        self.emit_label(&end);
    }

    fn emit_asm(&mut self, asm: &AsmStmt) {
        for line in &asm.lines {
            // Resolve each token to its NASM text.
            let mut fragments: Vec<String> = Vec::new();
            for tok in &line.tokens {
                let s = match tok {
                    AsmToken::Raw(s) => s.clone(),
                    // `%name` is the variable's *value*: a fully-sized memory
                    // operand. The `qword` qualifier lets NASM size otherwise
                    // ambiguous instructions like `idiv %b`.
                    AsmToken::Value(name) => match self.lookup(name) {
                        Some(info) => format!("qword [rbp - {}]", info.offset),
                        None => "qword [rbp - 0]".to_string(),
                    },
                    // `&name` is the variable's *address* (used with lea, etc.).
                    AsmToken::Addr(name) => match self.lookup(name) {
                        Some(info) => format!("[rbp - {}]", info.offset),
                        None => "[rbp - 0]".to_string(),
                    },
                };
                fragments.push(s);
            }
            let text = join_asm_fragments(&fragments);
            let _ = writeln!(self.cg.text, "    {}", text);
        }
    }

    // --- expressions ---------------------------------------------------------

    /// Emit `expr`; result lands in `rax` (ints/pointers) or `xmm0` (f64).
    fn emit_expr(&mut self, expr: &Expr) {
        match &expr.kind {
            ExprKind::IntLit(n) => self.emit(format!("mov rax, {}", n)),
            ExprKind::FloatLit(f) => {
                let label = self.cg.add_float(*f);
                self.emit(format!("movsd xmm0, [rel {}]", label));
            }
            ExprKind::CharLit(cp) => self.emit(format!("mov rax, {}", cp)),
            ExprKind::BoolLit(b) => self.emit(format!("mov rax, {}", if *b { 1 } else { 0 })),
            ExprKind::StringLit(s) => {
                let label = self.cg.add_string(s);
                self.emit(format!("lea rax, [rel {}]", label));
            }
            ExprKind::Ident(name) => self.emit_ident(name),
            ExprKind::QualifiedIdent { .. } => self.emit("xor rax, rax".to_string()),
            ExprKind::Ref { operand, .. } => self.emit_addr_of(operand),
            ExprKind::Deref { operand } => {
                let ty = expr.ty.clone().unwrap_or(Type::I64);
                self.emit_expr(operand); // rax = pointer
                if matches!(ty, Type::F64) {
                    self.emit("movsd xmm0, [rax]".to_string());
                } else if is_struct_type(&ty, self.cg) {
                    // pointer-to-struct: keep the pointer in rax
                } else {
                    self.emit("mov rax, [rax]".to_string());
                }
            }
            ExprKind::Unary { op, operand } => self.emit_unary(*op, operand, expr),
            ExprKind::Binary { op, left, right } => self.emit_binary(*op, left, right, expr),
            ExprKind::Cast { .. } => self.emit("xor rax, rax".to_string()),
            ExprKind::Call { callee, args } => self.emit_call(callee, args, expr),
            ExprKind::Field { object, field } => self.emit_field(object, field, expr),
            ExprKind::StructInit { name, fields } => self.emit_struct_init(name, fields, expr),
        }
    }

    fn emit_ident(&mut self, name: &str) {
        let info = match self.lookup(name) {
            Some(i) => i.clone(),
            None => {
                self.emit(format!("xor rax, rax ; unknown ident {}", name));
                return;
            }
        };
        match &info.ty {
            Type::F64 => self.emit(format!("movsd xmm0, [rbp - {}]", info.offset)),
            Type::Named(_) | Type::Qualified(_, _) => {
                self.emit(format!("lea rax, [rbp - {}]", info.offset))
            }
            _ => self.emit(format!("mov rax, [rbp - {}]", info.offset)),
        }
    }

    /// Emit the address of an lvalue expression into rax.
    fn emit_addr_of(&mut self, expr: &Expr) {
        match &expr.kind {
            ExprKind::Ident(name) => {
                if let Some(info) = self.lookup(name) {
                    self.emit(format!("lea rax, [rbp - {}]", info.offset));
                } else {
                    self.emit(format!("xor rax, rax ; addr of unknown {}", name));
                }
            }
            ExprKind::Field { object, field } => {
                let obj_ty = object.ty.clone().unwrap_or(Type::Void);
                let struct_name = receiver_struct(&obj_ty).unwrap_or_default();
                let idx = self.cg.field_index(&struct_name, field);
                self.emit_expr(object); // rax = base pointer
                if idx > 0 {
                    self.emit(format!("add rax, {}", idx as i64 * 8));
                }
            }
            ExprKind::Deref { operand } => self.emit_expr(operand), // &*p == p
            _ => self.emit_expr(expr),
        }
    }

    fn emit_unary(&mut self, op: UnaryOp, operand: &Expr, expr: &Expr) {
        let ty = expr.ty.clone().unwrap_or(Type::I64);
        match op {
            UnaryOp::Neg => {
                if matches!(ty, Type::F64) {
                    self.emit_expr(operand);
                    self.emit("xorpd xmm1, xmm1".to_string());
                    self.emit("subsd xmm1, xmm0".to_string());
                    self.emit("movsd xmm0, xmm1".to_string());
                } else {
                    self.emit_expr(operand);
                    self.emit("neg rax".to_string());
                }
            }
            UnaryOp::Not => {
                self.emit_expr(operand);
                self.emit("xor rax, 1".to_string());
            }
            UnaryOp::Deref => {
                self.emit_expr(operand);
                self.emit("mov rax, [rax]".to_string());
            }
            UnaryOp::Ref | UnaryOp::RefMut => self.emit_addr_of(operand),
        }
    }

    fn emit_binary(&mut self, op: BinaryOp, left: &Expr, right: &Expr, expr: &Expr) {
        let ty = expr.ty.clone().unwrap_or(Type::I64);
        if matches!(ty, Type::F64) {
            self.emit_expr(left);
            self.emit("sub rsp, 8".to_string());
            self.emit("movsd [rsp], xmm0".to_string());
            self.emit_expr(right);
            self.emit("movsd xmm1, xmm0".to_string());
            self.emit("movsd xmm0, [rsp]".to_string());
            self.emit("add rsp, 8".to_string());
            match op {
                BinaryOp::Add => self.emit("addsd xmm0, xmm1".to_string()),
                BinaryOp::Sub => self.emit("subsd xmm0, xmm1".to_string()),
                BinaryOp::Mul => self.emit("mulsd xmm0, xmm1".to_string()),
                BinaryOp::Div => self.emit("divsd xmm0, xmm1".to_string()),
                _ => {}
            }
        } else {
            self.emit_expr(left);
            self.emit("push rax".to_string());
            self.emit_expr(right);
            self.emit("mov rbx, rax".to_string());
            self.emit("pop rax".to_string());
            match op {
                BinaryOp::Add => self.emit("add rax, rbx".to_string()),
                BinaryOp::Sub => self.emit("sub rax, rbx".to_string()),
                BinaryOp::Mul => self.emit("imul rax, rbx".to_string()),
                BinaryOp::Div => {
                    self.emit("cqo".to_string());
                    self.emit("idiv rbx".to_string());
                }
                BinaryOp::Mod => {
                    self.emit("cqo".to_string());
                    self.emit("idiv rbx".to_string());
                    self.emit("mov rax, rdx".to_string());
                }
                _ => {}
            }
        }
    }

    fn emit_field(&mut self, object: &Expr, field: &str, expr: &Expr) {
        let obj_ty = object.ty.clone().unwrap_or(Type::Void);
        let struct_name = receiver_struct(&obj_ty).unwrap_or_default();
        let idx = self.cg.field_index(&struct_name, field);
        let field_ty = expr
            .ty
            .clone()
            .unwrap_or_else(|| self.cg.field_decl_type(&struct_name, field));
        self.emit_expr(object); // rax = base pointer
        if matches!(field_ty, Type::F64) {
            self.emit(format!("movsd xmm0, [rax + {}]", idx as i64 * 8));
        } else if is_struct_type(&field_ty, self.cg) {
            if idx > 0 {
                self.emit(format!("add rax, {}", idx as i64 * 8));
            }
        } else {
            self.emit(format!("mov rax, [rax + {}]", idx as i64 * 8));
        }
    }

    fn emit_struct_init(&mut self, name: &StructName, fields: &[(String, Expr)], expr: &Expr) {
        let struct_name = name.base().to_string();
        let decl_fields: Vec<(String, Type)> = self
            .cg
            .structs
            .get(&struct_name)
            .map(|s| {
                s.fields
                    .iter()
                    .map(|f| (f.name.clone(), f.ty.clone()))
                    .collect()
            })
            .unwrap_or_default();

        let base = self.slot(key_of(expr));

        if decl_fields.is_empty() {
            // Unknown struct (shouldn't happen post-typecheck); still emit values.
            for (i, (_, fe)) in fields.iter().enumerate() {
                let slot = base - i as i64 * 8;
                self.emit_expr(fe);
                self.emit(format!("mov [rbp - {}], rax", slot));
            }
        } else {
            for (idx, (decl_name, decl_ty)) in decl_fields.iter().enumerate() {
                if let Some((_, fexpr)) = fields.iter().find(|(n, _)| n == decl_name) {
                    let slot = base - idx as i64 * 8;
                    self.emit_field_store(fexpr, decl_ty, slot);
                }
            }
        }
        self.emit(format!("lea rax, [rbp - {}]", base));
    }

    fn emit_field_store(&mut self, fexpr: &Expr, decl_ty: &Type, slot: i64) {
        match decl_ty {
            Type::F64 => {
                self.emit_expr(fexpr);
                self.emit(format!("movsd [rbp - {}], xmm0", slot));
            }
            // A struct-typed field stores its value *inline*. The field value
            // evaluates to a pointer; copy its words into the slot. (Stdlib
            // value types are one word, matching the spec's 8-bytes-per-field.)
            Type::Named(n) | Type::Qualified(_, n) => {
                let nwords = self.cg.n_fields(n);
                self.emit_expr(fexpr); // rax = pointer to the source struct
                self.emit("mov rsi, rax".to_string());
                for i in 0..nwords {
                    self.emit(format!("mov rcx, [rsi + {}]", i as i64 * 8));
                    self.emit(format!("mov [rbp - {}], rcx", slot - i as i64 * 8));
                }
            }
            _ => {
                self.emit_expr(fexpr);
                self.emit(format!("mov [rbp - {}], rax", slot));
            }
        }
    }

    // --- calls ---------------------------------------------------------------

    fn emit_call(&mut self, callee: &Expr, args: &[Expr], call_expr: &Expr) {
        if let ExprKind::Field { object, field } = &callee.kind {
            let recv_ty = object.ty.clone().unwrap_or(Type::Void);
            if let Some(struct_name) = receiver_struct(&recv_ty) {
                let is_method = self.cg.has_method(&struct_name, field);
                if is_method {
                    self.emit_method_call(&struct_name, field, object, &recv_ty, args, call_expr);
                    return;
                }
            }
        }
        let fname = match &callee.kind {
            ExprKind::Ident(n) => n.clone(),
            ExprKind::QualifiedIdent { module, name } => {
                // Associated method `Struct::method` → label `Struct_method`.
                // A `module::function` qualifier keeps just the function name.
                if self.cg.has_method(module, name) {
                    format!("{}_{}", module, name)
                } else {
                    name.clone()
                }
            }
            _ => {
                self.emit("xor rax, rax ; uncallable".to_string());
                return;
            }
        };

        let pushed = self.eval_args(args, None);
        self.load_args_from_stack(&pushed);
        self.emit(format!("call {}", fname));
        self.materialize_struct_return(call_expr);
    }

    fn emit_method_call(
        &mut self,
        struct_name: &str,
        method: &str,
        receiver: &Expr,
        recv_ty: &Type,
        args: &[Expr],
        call_expr: &Expr,
    ) {
        let conv = self
            .cg
            .find_method(struct_name, method)
            .map(self_convention)
            .unwrap_or(SelfConv::None);

        let receiver_arg = !matches!(conv, SelfConv::None);
        let pushed = self.eval_args(
            args,
            if receiver_arg {
                Some((receiver, recv_ty))
            } else {
                None
            },
        );
        self.load_args_from_stack(&pushed);

        self.emit(format!("call {}_{}", struct_name, method));
        self.materialize_struct_return(call_expr);
    }

    /// After a call that returns a struct (value in rax(:rdx)), store the words
    /// into the call's result slot and leave a *pointer* to it in rax, restoring
    /// the "struct value == pointer in rax" invariant for downstream consumers.
    fn materialize_struct_return(&mut self, call_expr: &Expr) {
        let ty = match &call_expr.ty {
            Some(t) => t.clone(),
            None => return,
        };
        if !is_struct_type(&ty, self.cg) {
            return;
        }
        let nwords = self.cg.n_fields(&receiver_struct(&ty).unwrap_or_default());
        let slot = self.slot(key_of(call_expr));
        if slot == 0 {
            return; // no slot was allocated (shouldn't happen for struct returns)
        }
        match nwords {
            0 | 1 => {
                self.emit(format!("mov [rbp - {}], rax", slot));
            }
            2 => {
                self.emit(format!("mov [rbp - {}], rax", slot));
                self.emit(format!("mov [rbp - {}], rdx", slot - 8));
            }
            _ => {
                // >2 words returned by pointer: rax already points at it. Copy
                // defensively into our slot so it survives.
                self.emit("mov rsi, rax".to_string());
                for i in 0..nwords {
                    self.emit(format!("mov rcx, [rsi + {}]", i as i64 * 8));
                    self.emit(format!("mov [rbp - {}], rcx", slot - i as i64 * 8));
                }
            }
        }
        self.emit(format!("lea rax, [rbp - {}]", slot));
    }

    /// Evaluate the (optional) receiver followed by `args`, pushing each onto
    /// the stack, and return the per-argument kind list in push order.
    fn eval_args(&mut self, args: &[Expr], receiver: Option<(&Expr, &Type)>) -> Vec<ArgVal> {
        let mut pushed = Vec::new();
        if let Some((recv, recv_ty)) = receiver {
            self.emit_receiver_pointer(recv, recv_ty);
            self.emit("push rax".to_string());
            pushed.push(ArgVal::Int);
        }
        for a in args {
            let aty = a.ty.clone().unwrap_or(Type::I64);
            if matches!(aty, Type::F64) {
                self.emit_expr(a);
                self.emit("sub rsp, 8".to_string());
                self.emit("movsd [rsp], xmm0".to_string());
                pushed.push(ArgVal::Float);
            } else {
                self.emit_expr(a);
                self.emit("push rax".to_string());
                pushed.push(ArgVal::Int);
            }
        }
        pushed
    }

    fn emit_receiver_pointer(&mut self, receiver: &Expr, recv_ty: &Type) {
        if recv_ty.is_ref() {
            self.emit_expr(receiver); // already a pointer value
        } else {
            match &receiver.kind {
                ExprKind::Ident(_) | ExprKind::Field { .. } | ExprKind::Deref { .. } => {
                    self.emit_addr_of(receiver)
                }
                _ => self.emit_expr(receiver), // temporary struct → pointer
            }
        }
    }

    /// Pop pushed argument values (reverse order) into ABI registers.
    fn load_args_from_stack(&mut self, pushed: &[ArgVal]) {
        let n_int = pushed.iter().filter(|a| matches!(a, ArgVal::Int)).count();
        let n_flt = pushed.iter().filter(|a| matches!(a, ArgVal::Float)).count();
        let mut int_idx = n_int;
        let mut flt_idx = n_flt;
        for a in pushed.iter().rev() {
            match a {
                ArgVal::Int => {
                    int_idx -= 1;
                    self.emit(format!("pop {}", INT_REGS[int_idx]));
                }
                ArgVal::Float => {
                    flt_idx -= 1;
                    let reg = FLOAT_REGS[flt_idx];
                    self.emit(format!("movsd {}, [rsp]", reg));
                    self.emit("add rsp, 8".to_string());
                }
            }
        }
    }
}

#[derive(Clone, Copy)]
enum ArgVal {
    Int,
    Float,
}

#[derive(Clone, Copy)]
enum SelfConv {
    None,
    Ref,
    MutRef,
    Move,
}

fn self_convention(f: &FnDecl) -> SelfConv {
    for p in &f.params {
        match p.kind {
            ParamKind::SelfRef => return SelfConv::Ref,
            ParamKind::SelfMutRef => return SelfConv::MutRef,
            ParamKind::SelfMove => return SelfConv::Move,
            _ => {}
        }
    }
    SelfConv::None
}

// ---------------------------------------------------------------------------
// Free helpers
// ---------------------------------------------------------------------------

fn param_type(p: &Param, enclosing: Option<&str>) -> Type {
    match &p.kind {
        ParamKind::Named { ty, .. } => ty.clone(),
        ParamKind::SelfRef => Type::Ref(Box::new(self_type(enclosing.unwrap_or("")))),
        ParamKind::SelfMutRef => Type::MutRef(Box::new(self_type(enclosing.unwrap_or("")))),
        ParamKind::SelfMove => self_type(enclosing.unwrap_or("")),
    }
}

fn param_name(p: &Param) -> String {
    match &p.kind {
        ParamKind::Named { name, .. } => name.clone(),
        _ => "self".to_string(),
    }
}

fn receiver_struct(ty: &Type) -> Option<String> {
    match ty {
        Type::I64 => Some("i64".to_string()),
        Type::F64 => Some("f64".to_string()),
        Type::Named(n) | Type::Qualified(_, n) => Some(n.clone()),
        Type::Ref(inner) | Type::MutRef(inner) => receiver_struct(inner),
        _ => None,
    }
}

fn is_primitive_extend_target(name: &str) -> bool {
    matches!(name, "i64" | "f64")
}

fn self_type(name: &str) -> Type {
    match name {
        "i64" => Type::I64,
        "f64" => Type::F64,
        other => Type::Named(other.to_string()),
    }
}

fn is_struct_type(ty: &Type, cg: &CodeGen) -> bool {
    match ty {
        Type::Named(n) | Type::Qualified(_, n) => cg.structs.contains_key(n),
        _ => false,
    }
}

fn round_up(n: i64, mult: i64) -> i64 {
    if n <= 0 {
        return 0;
    }
    ((n + mult - 1) / mult) * mult
}

fn round_up_16(n: i64) -> i64 {
    round_up(n, 16)
}

fn sanitize(label: &str) -> String {
    label.replace(|c: char| !(c.is_ascii_alphanumeric() || c == '_'), "_")
}

fn nasm_byte_list(s: &str) -> String {
    let mut parts: Vec<String> = s.bytes().map(|b| b.to_string()).collect();
    parts.push("0".to_string());
    parts.join(", ")
}

/// Join asm token fragments into a single NASM line, inserting a separating
/// space only where required. NASM needs whitespace to separate a mnemonic from
/// word-like operands; commas, brackets, and `.label` pieces are self-delimiting.
fn join_asm_fragments(frags: &[String]) -> String {
    let mut out = String::new();
    for frag in frags {
        if frag.is_empty() {
            continue;
        }
        if out.is_empty() {
            out.push_str(frag);
            continue;
        }
        let prev = out.chars().last().unwrap();
        let next = frag.chars().next().unwrap();
        if asm_needs_space(prev, next) {
            out.push(' ');
        }
        out.push_str(frag);
    }
    out
}

fn asm_needs_space(prev: char, next: char) -> bool {
    // No space before these.
    if matches!(next, ',' | ':' | ']') {
        return false;
    }
    // No space after these.
    if matches!(prev, '[' | '.') {
        return false;
    }
    true
}
